//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newsletters.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public string C_ID { get; set; }
        public string email { get; set; }
        public string source { get; set; }
        public string reason { get; set; }
    }
}
